# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            'Donato Onorato'
tagline:          
description:      'Studying Mathematical Economics <a href = "https://economics.sas.upenn.edu/" target = "_blank">@UPenn</a>. Research Assistant <a href = "https://economics.sas.upenn.edu/" target = "_blank">@UPenn Econ. Dept.</a>'
url:              http://hyde.getpoole.com
baseurl:          '/onoratod.github.io/'

author:
  name:           'Donato Onorato'
  url:            

paginate:         5


# Custom vars
version:          

github:
  repo:           https://github.com/onoratod
